- .dockerignore
- .github/workflows/ci.yml
- Dockerfile
- JSON.cpp
- README.md
- lib/Optimize.cpp
* Dockerfile build
* Github Actions CI
> Dockerfile and CI

- .dockerignore
- .gitignore
- CMakeLists.txt
- JSON.cpp
- cmake/git_watcher.cmake
- include/anvill/Version.h
- lib/Version/CMakeLists.txt
- lib/Version/Version.cpp.in
Print detailed version information from `--version`
> Add version info

- .github/workflows/ci.yml
- scripts/emit-artifact.sh
Automatically make a release and bump version on each CI success
> Create Rolling Github Releases

- python/anvill/dwarf.py
- python/anvill/dwarf_type.py
- setup.py
Add types that were not previously committed.
> add missing dwarf types

- python/anvill/__init__.py
- python/anvill/arch.py
- python/anvill/binja.py
- python/anvill/dwarf.py
- python/anvill/dwarf_type.py
- python/anvill/exc.py
- python/anvill/function.py
- python/anvill/ida.py
- python/anvill/loc.py
- python/anvill/mem.py
- python/anvill/os.py
- python/anvill/program.py
- python/anvill/type.py
- python/anvill/var.py
This formats all of the python code with black
what you think chief?
> Format with black

- README.md
- python/anvill/binja.py
- setup.py
> Removes python-magic dependency and Updates README.md

- CMakeLists.txt
- Dockerfile
* Install Anvill python to a virtualenv, if it exists
* Make Dockerfile create a virtualenv, so the Python API is installed in the `dist` container.
> Install python to venv

- CMakeLists.txt
- JSON.cpp
- include/anvill/Lift.h
- include/anvill/MCToIRLifter.h
- include/anvill/Util.h
- lib/Lift.cpp
- lib/MCToIRLifter.cpp
- lib/Optimize.cpp
- lib/Util.cpp
@pgoodman let me know if this is okay with you.
> Move native-to-lifted piping code from MCToIRLifter

- bin/JSON.cpp
- lib/Lift.cpp
- lib/MCToIRLifter.cpp
* Small bug fix regarding placement new
* Add more comments
> Add comments and one small bugfix

- Dockerfile
- bin/Bitcode.cpp
- cmake/vcpkg_helper.cmake
- include/anvill/Decl.h
- lib/Version/CMakeLists.txt
Required for https://github.com/trailofbits/cxx-common/pull/677 and https://github.com/trailofbits/cxx-common/pull/679
> vcpkg: Support Windows and arm64

- bin/Bitcode.cpp
- include/anvill/Analyze.h
- include/anvill/Program.h
- lib/Analyze.cpp
- lib/Optimize.cpp
- lib/Program.cpp
- scripts/roundtrip.py
* Detect when a reference falls into the middle of a known variable
* Detect when a reference falls into the middle of a known byte range
> Better detection of references in Anvill

- CMakeLists.txt
- CMakeLists_vcpkg.txt
- Dockerfile
> Remove Python2.7 support

- lib/Lift.cpp
- lib/MCToIRLifter.cpp
Modifies lifting to ignore functions that do not have mapped bytes in the JSON spec.
> Do not lift functions that are not in the JSON spec

- anvill/python/anvill/binja.py
Add `TypeCache` to maintain the program level cache for binja to anvill type conversion instead of using the local cache for each type.
> Type cache in program for bn type conversion

- anvill/include/anvill/ABI.h
- anvill/include/anvill/Providers/TypeProvider.h
- anvill/python/anvill/binja.py
- anvill/src/ABI.cpp
- anvill/src/Lifters/DataLifter.cpp
- anvill/src/Lifters/EntityLifter.cpp
- anvill/src/Lifters/EntityLifter.h
- anvill/src/Lifters/FunctionLifter.cpp
- anvill/src/Lifters/ValueLifter.cpp
- anvill/src/Lifters/ValueLifter.h
- anvill/src/Providers/TypeProvider.cpp
- libraries/anvill_passes/src/SplitStackFrameAtReturnAddress.cpp
- libraries/anvill_passes/src/SplitStackFrameAtReturnAddress.h
- tools/decompile-json/src/main.cpp
Initial changes for value lifter.
> Value Lifter

- libraries/anvill_passes/src/RecoverEntityUseInformation.cpp
Get pointer size in bits while replacing xrefs uses with the entity.
> Fix type size

- libraries/anvill_passes/src/InstructionFolderPass.cpp
The changes fix the segfault in the instruction folder pass and avoid infinite folding of the Phi node due to cast instructions.
Ref: #150
> Fix segfault instruction folder pass

- anvill/python/anvill/binja/bnprogram.py
- anvill/python/anvill/ida/idaprogram.py
- anvill/python/anvill/program.py
Fixes issue https://github.com/lifting-bits/anvill/issues/156
> Exporter: Update elf thunk resolution

- anvill/python/anvill/__main__.py
- anvill/python/anvill/binja/__init__.py
- anvill/python/anvill/ida/__init__.py
- anvill/python/anvill/ida/idaprogram.py
This fixes issue https://github.com/lifting-bits/anvill/issues/170
> Exporter: Add base_address option

- anvill/python/anvill/binja/typecache.py
The reference type of named references could be None. Recover it as an integer type with type width or address size.
> Fix handling of unknown named references

- tools/decompile-json/src/main.cpp
Update the naming of the function declaration in IR.
> Update function decl naming

- anvill/python/anvill/__main__.py
- anvill/python/anvill/binja/bnprogram.py
- anvill/python/anvill/binja/callingconvention.py
- anvill/python/anvill/binja/typecache.py
- anvill/python/anvill/logging.ini
- anvill/python/anvill/util.py
- setup.py
Add logging framework to python script and enable verbose mode
> Add logger

- .github/workflows/anghabench-after-build.yml
- .github/workflows/anghabench-cron-jobs.yml
- .gitmodules
- ci/install_binja.sh
- scripts/build.sh
- scripts/run-on-anghabench.sh
* Add build.sh script to build/package/install anvill
* Update binja
* Add lifting-tools-ci as submodule
* Add github actions yml to start DO instances to run tests
> Support Anvill CI Runs against AnghaBench

- anvill/python/CMakeLists.txt
- ci/install_binja.sh
- scripts/build.sh
- scripts/run-on-anghabench.sh
* Fixes to install paths to work in more installation scenarios
> Install paths fix

- .github/workflows/anghabench-after-build.yml
- .github/workflows/build.yml
- ci/angha_1k_test_settings.json
- scripts/test-angha-1k.sh
* Gate builds by the 1K AnghaBench test
* Currently Only tests Anvill-Python, WIP to add decompile-json support
> Gate builds by testrun against AnghaBench 1K

- .github/workflows/build.yml
- Dockerfile
- README.md
- scripts/build.sh
Move cxx-common from trailofbits to lifting-bits org
> Move cxx-common to lifting-bits

- anvill/python/anvill/binja/typecache.py
- libraries/anvill_passes/src/BrightenPointerOperations.cpp
Fix handling of anonymous struct/union and seg fault in pointer lifter
> Fix type cache for anony types and pointer lifter

- anvill/src/TypeSpecification.cpp
- libraries/anvill_passes/src/RecoverStackFrameInformation.cpp
Fixes the stack frame ptr getting inserted before PHI node causing type cast error. 
Ref #232
> Fix insert point for stack frame ptr

- anvill/python/anvill/binja/table.py
Instruction `info` can be none. Add missing check for it.
> Add check for None

- anvill/python/anvill/binja/table.py
Sometime the jump target anvill is asking about is... NoneType. Do some sanity checking against this edge case.
> Guard against jump target detection not returning a valid jump target

- anvill/python/anvill/__main__.py
- anvill/python/anvill/binja/bnprogram.py
- anvill/python/anvill/binja/table.py
- anvill/python/anvill/program.py
- anvill/src/Lifters/FunctionLifter.cpp
Sometimes bv.functions has entries that... point to the middle of an existing function? Do a better check against the function cache.
Also adds more debug prints.
> Improve function cache

- anvill/python/anvill/binja/bnfunction.py
- anvill/python/anvill/binja/bnvariable.py
* Makes binja's fictional sections executable instead of not executable.
> change the fiction we use for binja's fictional sections to be executable

- scripts/run-on-anghabench.sh
* Save CI artifacts to DO after lifting
> Save CI artifacts to DO

- ci/angha_1k_test_settings.json
- libraries/anvill_passes/src/InstructionFolderPass.cpp
- libraries/anvill_passes/src/LowerRemillMemoryAccessIntrinsics.cpp
Fix lowering of memory op intrinsics for float80
Ref: https://github.com/lifting-bits/remill/pull/539
> fix replace memory op for float80

- lib/Optimize.cpp
- lib/Passes/ConvertXorsToCmps.cpp
> Attempt xor convert

- anvill/tests/anvill_passes/data/xor_removal.ll
- anvill/tests/anvill_passes/data/xor_removal_noremove.ll
- anvill/tests/anvill_passes/src/XorConversionPass.cpp
- lib/Optimize.cpp
- lib/Passes/ConvertXorsToCmps.cpp
Comments, test, and simplification of xor removal pass.
> Invert more xor (with tests)

- .github/workflows/build.yml
- .gitignore
- CMakePresets.json
- scripts/build-preset.sh
Use CMakePresets to build. This will be more documented at a later point, but its extremely handy for building multiple lifting tools into a single workspace.
* Use CMakePresets.json to do builds
* Add a script to build with presets
* Test CMakePresets.json in CI
> Use cmake presets

- include/anvill/Passes/Constraints.h
- lib/Passes/SlicerVisitor.h
This fixes a build issues I am experiencing on Ubuntu 21.10 with the LLVM 13 vcpkg
> Add missing include headers

- scripts/build-preset.sh
* Output the whole log and not last 10 lines
> More verbose errors on build fails to debug GHA

- lib/Passes/ConvertXorsToCmps.cpp
- tests/anvill_passes/src/XorConversionPass.cpp
- tests/tools/src/TypeSpecification.cpp
Fix pedantic C++ errors regarding use of structured binding and variables, get rid of unused variable
> Fix CI compilation issues

- README.md
- bin/Decompile/Main.cpp
- lib/Arch/AArch32_C.cpp
- lib/Arch/AArch64_C.cpp
- lib/Arch/AllocationState.cpp
- lib/Arch/AllocationState.h
- lib/Arch/Arch.h
- lib/Arch/SPARC32_C.cpp
- lib/Arch/SPARC64_C.cpp
- lib/Arch/X86_64_SysV.cpp
- lib/Arch/X86_C.cpp
- lib/Arch/X86_FastCall.cpp
- lib/Arch/X86_StdCall.cpp
- lib/Arch/X86_ThisCall.cpp
- lib/JSON.cpp
- lib/Lifters/FunctionLifter.cpp
- lib/Lifters/ValueLifter.cpp
- lib/Optimize.cpp
- lib/Passes/TransformRemillJumpIntrinsics.cpp
- lib/Specification.cpp
- lib/Type.cpp
- scripts/build.sh
- scripts/run-on-anghabench.sh
- tests/anvill_passes/src/BrightenPointers.cpp
> Remove compatibility for LLVM < 14

- .gitignore
- lib/Passes/RecoverBasicStackFrame.cpp
Should fix trailofbits/IRENE#99 but I haven't had the chance to test it yet, so it's a draft for now
> Fix backwards stack

- cmake/packaging.cmake
Don't include CPack if it's previously included
also fix cpack package name and description
> Fix cpack include

- .github/workflows/build.yml
requires the .outputs. to actually access the variable
> fix typo in variable name for build_job_count

- tests/tools/src/TypeSpecification.cpp
> tests: Trigger padding for packed vs non-packed type encoding test

- data_specifications/specification.proto
- include/anvill/Declarations.h
- include/anvill/Utils.h
- lib/Arch/Arch.cpp
- lib/Arch/Arch.h
- lib/Arch/StubABI.cpp
- lib/CMakeLists.txt
- lib/Declarations.cpp
- lib/Lifters/BasicBlockLifter.cpp
- lib/Lifters/FunctionLifter.cpp
- lib/Optimize.cpp
- lib/Passes/RemoveCallIntrinsics.cpp
- lib/Passes/ReplaceRemillFunctionReturnsWithAnvillFunctionReturns.cpp
- lib/Passes/ReplaceStackReferences.cpp
- lib/Protobuf.cpp
- lib/Protobuf.h
- lib/Utils.cpp
Expands the generality of all valuedecls to allow splitting across multiple registers etc
> Rework load lifted value and store native to operate over composite low level storage

- include/anvill/Passes/CodeQualityStatCollector.h
- lib/Optimize.cpp
- lib/Passes/CodeQualityStatCollector.cpp
* Always enable these statistics
* Collect loads/stores to __anvill_sp
> Metrics for Reference Recovery
