lifting-bits/anvill

setup.py
`magic` is a dependency of anvill and isn't currently installed with setup.py 
This PR adds it to setup.py so `python setup.py install` adds all dependencies.
=> Add python magic to setup.py

lib/Lift.cpp
Clang currently crashes on our use of inline assembly references. Guard the new behavior via a feature flag (see issue #72), and default to old behavior.
=> Gate inline assembly references of registers not in the spec

lib/Optimize.cpp
There was a type mismatch bug in the code responsible for lowering type operations. 
The fix is to access the function return type, instead of the actual function type. 
This bug can be caught with a debug version of LLVM
=> Fix return type mismatch bug

python/anvill/__main__.py, python/anvill/binja.py, python/anvill/util.py, python/anvill/var.py, setup.py
Add warning logs for type classes that are not handled. Added checks if binja fails to get segment information for some variable address such as  `__elf_headers`.
=> Handling of missing type class

python/anvill/binja.py
Binja function `get_reg_value` will fail for temp register. The PR adds check for the temp registers and only run pointers lookup on MLIL in such case.
=> Fix handling of temp registers

lib/Analyze.cpp, python/anvill/binja.py
The PR fixes the handling of variables with invalid addresses. It does not get added to the global variables list. Also, fixes the assertion error due to `unimplemented` or `undef` instructions as one of LLIL operand.
=> Handling of variables with invalid address

lib/Lift.cpp, python/anvill/binja.py
The PR fixes the handling of Named Type references in the binary. It recovers them as a block of bytes and lifts them. Recovering the elements of named types is still in the TODO list and will be handled in future PR.
=> Handling of Named Type references

anvill/python/CMakeLists.txt
Do not try to install to system packages if doing a dev install. Avoid the following error message:
```
running install
error: You must specify --record or --root when building system packages
```
=> Only install to system packages if not doing a dev install

.github/workflows/build.yml
Limit MacOS to LLVM 11 since we have a limited number of MacOS runners.
=> Update build.yml to limit MacOS CI Runners

.github/workflows/build.yml, anvill/python/CMakeLists.txt, cmake/options.cmake
Changes:
1. Enables the tests and the install target in the default configuration
2. Fixes an issues with packaging, which didn't work correctly due to how DESTDIR was handled
=> CI: Update default CMake settings, fix package generation

anvill/python/anvill/binja.py, anvill/python/anvill/type.py, anvill/src/Analyze.cpp, anvill/src/Optimize.cpp
The PR fixes the binja script crash due to zero-sized array, unsupported x87 status & control regs, and missing data variable for an address. Also, handle named type references as the function parameters.
=> Fix crash array size, unsupported reg, missing data var

anvill/include/anvill/Program.h, anvill/src/Analyze.cpp, anvill/src/Optimize.cpp, anvill/src/Program.cpp
Temporary fix to ByteSequence such that we know what the real start address of the sequence should be. This is a temporary holdover until we eliminate ByteSequence.
Fix a copypasta bug (we had a local named `ret` and a function-level variable named `ret`)
=> Fix bytesequence and copypasta

anvill/src/Analyze.cpp, anvill/src/Lift.cpp, anvill/src/MCToIRLifter.cpp, anvill/src/Optimize.cpp, anvill/src/Program.cpp
Sets internal linkage to `__anvill_reg_*` this enables optimizing them away later on so that they don't pollute the output bitcode.
=> Internalize `__anvill_reg_*` global variables

anvill/python/anvill/binja.py, anvill/src/Lifters/DataLifter.cpp, anvill/src/Lifters/EntityLifter.h, anvill/src/Lifters/ValueLifter.cpp
Fix stack overflow in the value lifter due to self-pointing references. It also has fixes for handling type `int24_t` recognized by binary ninja.
=> Fix stack overflow due to self pointing refs

anvill/src/Lifters/FunctionLifter.cpp, anvill/src/Lifters/ValueLifter.cpp
The changes fix the function type mismatch due to incorrect `func_decl` ea.
=> Fix function type mismatch

anvill/CMakeLists.txt, anvill/python/anvill/arch.py, anvill/python/anvill/binja.py, anvill/python/anvill/ida.py, anvill/src/Arch/AArch32_C.cpp, anvill/src/Arch/Arch.cpp, anvill/src/Arch/Arch.h, anvill/src/Lifters/DataLifter.cpp, anvill/src/Lifters/ValueLifter.cpp
Add support for spec recovery from armv7 and thumb2 binaries. The IR generation for thumb2 is not supported yet. Also, need a remill patch to handle pc-relative addressing for armv7 for lifting the test binaries.
=> AArch32 support

anvill/python/anvill/imageparser/__init__.py, anvill/python/anvill/imageparser/elfparser.py, setup.py
A binary may not have dynamic symbol table or string table. The changes avoid runtime errors and add a warning log for such cases.
=> fix runtime error in image parser

anvill/src/Analysis/Utils.cpp, anvill/src/Optimize.cpp, libraries/anvill_passes/CMakeLists.txt, libraries/anvill_passes/include/anvill/Transforms.h, libraries/anvill_passes/src/TransformRemillJumpIntrinsics.cpp
Added a pass that identifies if a return instruction is lifted as an indirect jump and transforms the remill intrinsic calls for them.
=> Fix intrinsic for return instructions lifted as indirect jump

anvill/python/anvill/binja/callingconvention.py
The Floating-point argument registers for Aarch64 are missing from the list.
=> Floating point argument registers for Aarch64

anvill/python/anvill/__main__.py
Provide a useful error message if BinaryNinja could not initialize a BinaryView.
=> Sanity check that a BinaryView was created

anvill/python/anvill/binja/bnfunction.py
Previously anvill would emit TEMP registers in the spec. Add a check not to do this.
=> Do not emit temp registers in spec

anvill/python/anvill/binja/bnfunction.py
Disable filling memory bytes for the function having `thumb2` instruction sets in spec.
=> Disable functions with thumb2 instructions in spec

anvill/CMakeLists.txt, anvill/python/CMakeLists.txt, cmake/options.cmake
This is generally useful if someone doesn't want to worry about the Python setup, and I also use it in cxx-common.
(commit messages aren't the most accurate, just look at the diff 🙂 )
=> cmake: Add option to not touch Python

anvill/python/anvill/binja/bnfunction.py
Ref: #220 
Implements `is_noreturn` function to set the spec for noreturn function correctly.
=> Handle noreturn function in binja script

anvill/src/Optimize.cpp, libraries/anvill_passes/CMakeLists.txt, libraries/anvill_passes/include/anvill/Transforms.h, libraries/anvill_passes/src/ConvertXorToCmp.cpp, libraries/anvill_passes/tests/CMakeLists.txt, libraries/anvill_passes/tests/data/xor_conversion.ll, libraries/anvill_passes/tests/data/xor_conversion_nochange.ll, libraries/anvill_passes/tests/src/XorConversionPass.cpp
Convert some specific instances of the form:
```
%c = icmp pred, op1, op2
%x = xor i1 %c , true
```
into:
```
%c = icmp !pred, op1, op2
%x = %c
```
And update uses of BranchInst and SelectInst. Bail out if uses include things that are not branches or selects.
This comes up often enough in lifted bitcode to do this transform.
=> Anvill xor converter pass

anvill/include/anvill/Analysis/CrossReferenceResolver.h, anvill/python/anvill/binja/typecache.py, anvill/src/Analysis/CrossReferenceResolver.cpp, libraries/anvill_passes/src/BrightenPointerOperations.cpp, libraries/anvill_passes/src/RecoverStackFrameInformation.cpp
The stack offset was not getting sign-extended while resolving stack frame references. Fix the error due to the stripping up of the reference address.
=> Stack offset error

anvill/python/anvill/binja/table.py
Add checks for `jmp` and `tailcall` instruction after converting them to MLIL.
=> Check for jmp and tailcall instructions

libraries/anvill_passes/src/BrightenPointerOperations.cpp, libraries/anvill_passes/src/ConvertXorToCmp.cpp, libraries/anvill_passes/src/InstructionFolderPass.cpp, libraries/anvill_passes/src/LowerRemillMemoryAccessIntrinsics.cpp, libraries/anvill_passes/src/LowerRemillUndefinedIntrinsics.cpp, libraries/anvill_passes/src/LowerTypeHintIntrinsics.cpp, libraries/anvill_passes/src/RecoverEntityUseInformation.cpp, libraries/anvill_passes/src/RecoverStackFrameInformation.cpp, libraries/anvill_passes/src/RemoveDelaySlotIntrinsics.cpp, libraries/anvill_passes/src/RemoveErrorIntrinsics.cpp, libraries/anvill_passes/src/RemoveRemillFunctionReturns.cpp, libraries/anvill_passes/src/SinkSelectionsIntoBranchTargets.cpp, libraries/anvill_passes/src/SplitStackFrameAtReturnAddress.cpp, libraries/anvill_passes/src/TransformRemillJumpIntrinsics.cpp, libraries/anvill_passes/src/Utils.cpp, libraries/anvill_passes/src/Utils.h
@pgoodman 
I wanted to check in and make sure that I have the right idea here. I looked through Anvill's passes for spots where we replace instructions and copied the metadata across.
The remaining passes seem to either be removing instructions entirely (so no need to propagate anything) or the new instructions don't seem to map to an existing one (`RecoverStackFrameInformation` and `SplitStackFrameAtReturnAddress`). So I've left those untouched.
Also, is there a way to verify this patch? From what I can see, the unit tests just run the pass over some LLVM IR and check that it succeeds.
=> Propagate instruction metadata in passes

anvill/python/anvill/binja/bnfunction.py, anvill/python/anvill/binja/bnprogram.py, anvill/src/Arch/AArch64_C.cpp, tools/decompile-json/src/main.cpp
Ignore `xzr` register for arm64 and unsupported registers in x86 binaries. Handle i128 parameter types in arm64.
=> Handle i128 arg types for arm64

anvill/include/anvill/Analysis/CrossReferenceResolver.h, anvill/src/Analysis/CrossReferenceResolver.cpp, anvill/src/Analysis/Utils.cpp, libraries/anvill_passes/src/RecoverEntityUseInformation.cpp, libraries/anvill_passes/src/RecoverStackFrameInformation.cpp, libraries/anvill_passes/src/RemoveRemillFunctionReturns.cpp, libraries/anvill_passes/src/TransformRemillJumpIntrinsics.cpp
Enabled caching of instruction in xref resolver to avoid exploding the states while doing the lookup and resolving cross references. The caching is also added while looking for the value derived from symbolic stack.
=> wip: enable caching instructions in xref resolver

anvill/python/anvill/arch.py, anvill/python/anvill/binja/bnfunction.py
The changes scan the registers and detect correct sub-architecture if xmm/ymm/zmm registers getting used. (#219)
=> Detect sub architecture of amd64 in python

anvill/src/Optimize.cpp, libraries/anvill_passes/CMakeLists.txt, libraries/anvill_passes/include/anvill/Transforms.h, libraries/anvill_passes/src/RemoveBranchAndFlagIntrinsics.cpp, libraries/anvill_passes/src/RemoveBranchAndFlagIntrinsics.h, libraries/anvill_passes/src/RemoveStackPointerCExprs.cpp, libraries/anvill_passes/src/RemoveStackPointerCExprs.h
This PR removes comparison and branch hint intrinsics to make decompiler output prettier. This is a temporary measure and in the future branch recovery should use these hints to remove them while simplifying the branch. An additional pass should exist in branch recovery that removes failed hints, but this pass should derive from the intrinsic pass infra that already exists on that branch
=> Adds Temporary Intrinsic Removal Pass

include/anvill/Declarations.h, include/anvill/Providers.h, lib/JSON.cpp, lib/Lifters/ValueLifter.cpp, lib/Providers/TypeProvider.cpp
This PR allows for some fairly ugly cooperation between the type provider and value lifter to avoid committing to default types for pointers without entities. In many cases, we use anvill to lift portions of a binary without lifting all of the entities. In this case the type provider is used to hint about whether we have knowledge about what exists at a given variable. In the presence of type providers that just provide a default address for a type this doesnt work, so the type provider now hints that decl it's returning doesnt imply any knowledge about this specific EA
=> Fix anvill commiting to default function types for all pointers

include/anvill/Providers.h, lib/Declarations.cpp, lib/Lifters/FunctionLifter.cpp, lib/Lifters/ValueLifter.cpp, lib/Passes/ConvertAddressesToEntityUses.cpp, lib/Providers/TypeProvider.cpp
Uses the explicit default version of the type provider when defaults are acceptable.
=> Uses Default Versions of Type Provider Functions when Needed

lib/Specification.cpp, lib/Specification.h
This PR allows specification to continue if some functions fail to allocate value decls for their parameters. We might want to consider passing the warnings up rather than displaying them.
=> Collect warnings when a single function fails to parse

lib/Optimize.cpp
Since we're not sure we need these, let's just comment them out until we start seeing IR that would benefit from DSE or sinking. I've documented this in #298 in case we need to reenable them.
=> Comment out passes that are slow with LLVM 14

.github/workflows/build.yml, Dockerfile, ci/install_binja.sh, ci/switcher.py, lib/Lifters/FunctionLifter.cpp, lib/Lifters/FunctionLifter.h
This PR gets anvill building against remill https://github.com/lifting-bits/remill/pull/617 and should encompass most of the anvill side changes to support mixed mode. The last thing to work out here is how we want to specify building the initial context per function ie. for a thumb labeled function we need an initial context with TM set to 1. One possibility is to have a context assignment list in the spec for functions
=> Tracks Decoding Context for Instructions in Worklist

tests/anvill_passes/src/SinkSelectionsIntoBranchTargets.cpp
Error I got:
```
In file included from /root/anvill/tests/anvill_passes/src/SinkSelectionsIntoBranchTargets.cpp:9:
In file included from /root/anvill/include/anvill/Passes/SinkSelectionsIntoBranchTargets.h:11:
In file included from /root/cxx-common/vcpkg/installed/x64-linux-rel/include/llvm/IR/PassManager.h:40:
In file included from /root/cxx-common/vcpkg/installed/x64-linux-rel/include/llvm/ADT/DenseMap.h:17:
In file included from /root/cxx-common/vcpkg/installed/x64-linux-rel/include/llvm/ADT/DenseMapInfo.h:20:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/tuple:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/utility:70:
In file included from …
```
=> Fix compilation on Ubuntu 22

bin/Decompile/Main.cpp, include/anvill/ABI.h, include/anvill/Lifters.h, include/anvill/Passes/RemoveAssignmentsToNextPC.h, lib/ABI.cpp, lib/CMakeLists.txt, lib/Optimize.cpp, lib/Passes/RemoveAssignmentsToNextPC.cpp
This is a temporary measure and will be superseded by #349. For now we call an intrinsic that signals a goto to address
=> Adds a control flow simplification pass to support idiomatic block gotos

lib/Passes/RemoveAssignmentsToNextPC.cpp, lib/Passes/ReplaceRemillFunctionReturnsWithAnvillFunctionReturns.cpp, lib/Passes/Utils.cpp, lib/Passes/Utils.h
This is a hack to better support the semantics of returns, in reality what we want here is for every block exiting control flow effect to be preceded by a live variable pack, maybe this can be achieved in #349
=> Force pack lives to occur before recovered anvill returns when replacing remill returns

lib/Lifters/BasicBlockLifter.cpp, lib/Lifters/FunctionLifter.cpp
Current tail calls dont pass the up to date memory pointer to the child block. We could fix this by just passing the resulting memory down to children, but this would not help for blocks that only native return. These blocks (if there is no memory read for the return value ie. if there is just a global write) can discard memory writes. This PR transforms memory writes to write into a memory ref hosted in the parent function. 
Im concerned that in the high level lift we may run into a similar issue, but lets deal with the immediate problem first
=> Keep memory consistent through basic block calls and returns
